### ISSUE TITLE
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by dhardiker** [yudielcurbelo/react-qr-scanner#20] opened 2024-01-13 13:08 UTC
Setup:
* @yudiel/react-qr-scanner v1.2.4
* React v18.2.0
* React Router DOM v6.21.2

I have a simple React app which needs to read a QR code and pass the contents to the backend API for a scoring system.

```tsx
<QrScanner
  onDecode={code => {
    console.log('Navigate to captured code:', code)
    navigate('/display-code', { state: { code } })        
  }}
  onError={error => {
    console.error(error?.message)
    throw error
  }}
/>
```

This QR Scanner works fine, except for if I call React Router's `navigate` (from the `useNavigate()` hook) it throws the following error:
```
ERROR
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at e.makeBufferFromCanvasImageData (http://localhost:3000/static/js/bundle.js:16610:34)
    at new e (http://localhost:3000/static/js/bundle.js:16607:69)
    at t.createBinaryBitmap (http://localhost:3000/static/js/bundle.js:17183:13)
    at t.decode (http://localhost:3000/static/js/bundle.js:17178:20)
    at n (http://localhost:3000/static/js/bundle.js:17170:21)
 ```
 
 Googling around, it appear to be a dirty dismount issue.
 
 My workaround is to throw the error away, and it all works fine:
 ```tsx
 <QrScanner
  onDecode={code => {
    console.log('Navigate to captured code:', code)
    navigate('/display-code', { state: { code } })        
  }}
  onError={error => {
    // We get this error message after capturing a code
    if (error?.message.startsWith("Failed to execute 'getImageData' on 'CanvasRenderingContext2D':")) return 
    // We should report all other errors
    console.error(error?.message)
    throw error
  }}
/>
```

Is there something missing I should be doing before calling `navigate`?

**Comment by yudielcurbelo** [comment] 2024-01-13 13:17
Try to set a state inside the onDecode and navigate inside an useEffect with dependency of that state.

**Comment by dhardiker** [comment] 2024-01-13 14:10
Here's the full code for the route I tried which had the same error:
```tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { Box, Button, Container, Typography } from "@mui/material"
import { Helmet } from "react-helmet-async"
import { useNavigate } from "react-router-dom"
import { QrScanner } from "@yudiel/react-qr-scanner";

const useCaptureCode = () => {
  const navigate = useNavigate()
  const [ code, setCode ] = useState<string | undefined>(undefined)
  const lastHandledCode = useRef<typeof code>(undefined)

  useEffect(() => {
    // We only want to handle when there is a code
    if (code === undefined) return

    // We only want to handle when the code has changed to stop repeats
    if (code === lastHandledCode.current) return
    lastHandledCode.current = code

    // Change the route
    console.log('Navigate to captured code:', code)
    navigate('/display-code', { state: { code } })
  }, [ navigate, code, lastHandledCode ])

  return useCallback((code: string) => setCode(code), [ setCode ])
}

export const Element: React.FC = () => {
  const navigate = useNavigate()
  const captureCode = useCaptureCode()

  return <>
    <Helmet>
      <title>Scan QR Code</title>
    </Helmet>
    <Container component="main">
      <Box
        sx={{
          marginTop: 8,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <Typography component="h1" variant="h5" marginBottom={3}>
          Scan QR Code
        </Typography>
        <QrScanner
          onDecode={captureCode}
          onError={error => {
            console.error(error?.message)
            throw error
          }}
        />
        <Button
          variant="contained"
          sx={{ marginTop: 1 }}
          onClick={() => navigate('/')}
        >
          Cancel Scan
        </Button>
      </Box>
    </Container>
  </>
}
```

I also tried the following, which made no difference either:
```tsx
setTimeout(() => {
  console.log('Navigate to captured code:', code)
  navigate('/display-code', { state: { code } })
}, 1000)
```

I have the full code here: https://github.com/dhardiker/dhardiker.github.io (although it doesn't have any of the changes from this particular comment pushed).

**Comment by mariusk** [comment] 2024-01-13 17:42
I'm seeing the same when removing the component from a view. Most likely an unmount issue where some resources are not cleaned out or checked while callbacks are still active.

**Comment by Karanpal97** [comment] 2024-01-16 02:50
Hi everyone,

I hope you're doing well. I'm currently facing an issue with the QrScanner package in one of my projects.  now I've encountered a problem.

The QR scanner is defaulting to the front camera, and I specifically need it to use the rear camera by default. I've tried setting the facingMode prop to "environment," but it seems to be having no effect.

Here's the relevant code snippet:

jsx

<QrScanner
  onScan={handleScan}
  onError={handleError}
  style={{ width: '100%' }}
  facingMode="environment"
/>

I've noticed that without the ability to use the rear camera, the functionality of the application is severely impacted.

I would greatly appreciate any assistance or suggestions on how to resolve this issue. Has anyone else experienced a similar problem or found a solution? Your insights would be immensely helpful!

Thank you in advance for your time and assistance.

**Comment by Karanpal97** [comment] 2024-01-16 02:51
Hi @mariusk  @dhardiker  @yudielcurbelo  @considerate ,

I hope you're doing well. I'm currently facing an issue with the QrScanner package in one of my projects. now I've encountered a problem.

The QR scanner is defaulting to the front camera, and I specifically need it to use the rear camera by default. I've tried setting the facingMode prop to "environment," but it seems to be having no effect.

Here's the relevant code snippet:

jsx

<QrScanner
onScan={handleScan}
onError={handleError}
style={{ width: '100%' }}
facingMode="environment"
/>

I've noticed that without the ability to use the rear camera, the functionality of the application is severely impacted.

I would greatly appreciate any assistance or suggestions on how to resolve this issue. Has anyone else experienced a similar problem or found a solution? Your insights would be immensely helpful!

Thank you in advance for your time and assistance.

**Comment by dhardiker** [comment] 2024-01-16 08:34
Hi @Karanpal97

As this is not the name issue, please can I ask you create a new one. I don’t know the answer but will take a look to see if I can find out later today.

**Comment by mariusk** [comment] 2024-01-16 08:36
Main issue or not, this is the solution to the camera facing issue:
```javascript
                        <QrScanner
                          constraints={{facingMode: 'environment'}}
                          onDecode={(result) => onDecode(result)}
                          onError={(error) => onError(error)} />
```

**Comment by yudielcurbelo** [comment] 2024-01-17 14:17
@dhardiker @mariusk  Could you verify if the issue is resolved in `1.2.5-beta.3`. Here is a sample [Sandbox ](https://codesandbox.io/p/sandbox/fancy-silence-rdpxlc) using the beta version.

**Comment by dhardiker** [comment] 2024-01-17 17:41
I was able to reproduce the above with 1.2.4 and by upgrading to 1.2.5-beta.3 the error no longer was reproduceable. Excellent and speedy work @yudielcurbelo!

**Comment by yudielcurbelo** [comment] 2024-01-17 18:36
Thank you for confirming. Version `1.2.6` is out and should be fixed. Closing the issue.

**Closed by yudielcurbelo** 2024-01-17 18:36 UTC

**Comment by mariusk** [comment] 2024-01-17 22:05
I can also confirm that the canvasrenderingcontext2d error is gone with 1.2.6. Thanks.
